### ISSUE TITLE
Filtering by usb* shows no devices, HTML is output as raw text

### ISSUE THREAD

**Issue by dshoreman** [kb100/i3blocks-usb#1]
When I use the usb script with i3blocks, the default output shows nothing at all as none of my USB devices are listed under `/dev/disk/by-id/` with the `usb-` prefix: they only appear with the `ata-` and `wwn-` prefixes.

If I change [line 19](https://github.com/kb100/i3blocks-usb/blob/master/usb#L19) to the following:
```bash
DEVICES=$(lsblk -lo NAME 2>/dev/null | grep -v 'sda' | grep -o 'sd.$')
```

and [line 80](https://github.com/kb100/i3blocks-usb/blob/master/usb#L80) in a similar way:
```bash
    PARTITIONS=$(lsblk -lo NAME 2>/dev/null | grep -o "$sdx"'.')
```

then the script appears to pick up the devices ok, but the output shown includes all the `<span/>` tags, along with extra garbled output:
![Screenshot of broken i3blocks/i3status](http://i.imgur.com/PkrXe1e.png)

I'm calling the usb script with the following lines in `~/.i3blocks.conf`:
```
[usb]
markup=pango
signal=1
interval=10
```

I noticed the markup parameter was only recently added to i3blocks, so I updated to latest (v1.3.r44 previously, now v1.4.r0) and reloaded i3, but it made no difference. Where could the issue lie?

I can strip all the HTML markup, but this of course won't colour any of the output. It does however solve the garbling issue, which is likely caused by the i3blocks output being longer than the i3bar is wide.

**Comment by kb100** [comment]
To test if your i3/i3blocks is the problem, try a test script

    [test]
    command=echo "<span color='red'>test</span>"

I'll take a closer look at your fix when I get time. If you figure it out before then, please fork the repo, commit your fix, and submit a pull request. Thanks for being the first contributor!

**Comment by dshoreman** [comment]
That doesn't work either, so I'm thinking I probably need an update to i3 itself, rather than just i3blocks.

Re the device fix, it's more a "works on my machine" situation. Using `lsblk -lo NAME 2>/dev/null | grep -v sda` works for me because I'm on a laptop with a single internal HDD. Anyone with SSD+HDD - or on a desktop machine with multiple drives - would end up needing to hack that line to exclude their internal devices manually.

I checked my version of udisks and it seems I'm still on 1.x - perhaps the usb aliases were only added in v2? When I attempted to install udisks2 through pacman, it bailed with "libgudev and libsystemd are in conflict". I'll have to wait until I can do a full system backup/update before I can test that properly.

**Comment by dshoreman** [comment]
Bingo! Turns out my old i3 was causing the [lack of] colour issue. I was on 4.8-3 before - updated to 4.10.2-1 and it works perfectly.

Still have to use `lsblk` instead of listing usb devices, but again, this is likely due to needing udisks2.

This is a great script though, thanks! If I can find the time I might tweak things to support a "blacklist" of sorts. Is that something you'd consider merging? For instance, `sdb1` is a hidden partition that will never be mounted, so it makes sense to not show it. I'm thinking along the lines of a file with a list of partition UUIDs to filter against.

**Comment by kb100** [comment]
@dshoreman The reasons that I originally used 

    ls -l /dev/disk/by-id/usb* 2>/dev/null | grep -o 'sd.$'

was exactly to exclude built-in partitions (for me this is 6!), I would definitely consider adding a blacklist feature.

**Comment by kb100** [comment]
@dshoreman I rewrote the whole script in python. It now supports ignore/blacklisting through the `config.py` file. Make sure to update your `i3blocks.conf` file to say `usb.py` instead of `usb`.

Let me know if this is sufficient for your uses. If so, close the issue.

**Comment by kb100** [comment]
Closing issue because I think it is fixed and haven't heard otherwise from the issuer. Make a new issue if problem still exists.

**Comment by dshoreman** [comment]
@kb100 Sorry for the delay, I've been away for the past week or two without an Internet connection. Before going away I updated my arch install, so I'll try out your new python version soon.
