### ISSUE TITLE
No output !

### ISSUE THREAD

**Issue by aleprovencio** [kb100/i3blocks-usb#2]
I get no output when doing the default config.  I get this error when running usb.py from the CLI:

	subprocess.CalledProcessError: Command '['lsblk', '-spndo', 'NAME']' returned non-zero exit status 1

**Comment by kb100** [comment]
Could you post the output of
    lsblk -spndo NAME

**Comment by aleprovencio** [comment]
It prints the help message, and it seems that both '-s' and '-p' are not valid options.

**Comment by kb100** [comment]
The -s option was added to 2.22 in 2012 and the -p option was added in 2.23 in 2013. I recommend you upgrade to something more recent. I'll add util-linux >= 2.23 as a dependency. Does upgrading solve your issue?

**Comment by aleprovencio** [comment]
Thank you kb100. I can't update right now but that might solve it so I'm closing this.

**Comment by kb100** [comment]
@aleprovencio You may want to check out the old commit 11bfbf44f464ce6da58b6c8d7d1a19ebb47aae03. It is written in bash and does not use lsblk. I decided to do a python rewrite, but you may find it useful.

**Comment by aleprovencio** [comment]
Indeed it does work this way, so I'll keep it until updating is possible. Thank you @kb100 !
