### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by Mahadras** [kb100/i3blocks-usb#3]
Hey,

I am using i3blocks with ArchLinux. I just installed i3block-usb but nothing shows up.
Just like in the example
[usb]
command=~/.config/i3blocks/blocks/i3blocks-usb/usb.py
markup=pango
signal=1
interval=10

I use this path for other scripts and they work perfectly.
I choose multiply USB's and they all got mounted successfully but still nothing on my i3bar.

Any approach to analize the problem?

Greets

**Comment by kb100** [comment]
Could you please post the output of the command `python3 usb.py`

**Comment by Mahadras** [comment]
Traceback (most recent call last):
  File "usb.py", line 184, in <module>
    output = SEPARATOR.join(outputs)
  File "usb.py", line 156, in getOutput
    return getUnencryptedPartitionOutput(path)
  File "usb.py", line 123, in getUnencryptedPartitionOutput
    if isReadOnly(path):
  File "usb.py", line 59, in isReadOnly
    return "ro" in getFSOptions(path)
  File "usb.py", line 54, in getFSOptions
    universal_newlines=True).strip()
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['findmnt', '-no', 'FS-OPTIONS', '/dev/sdb2']' returned non-zero exit status 1

**Comment by kb100** [comment]
Could you please post the output of the command

    findmnt -no FS-OPTIONS /dev/sdb2

**Comment by Mahadras** [comment]
There is no output for that command

**Comment by kb100** [comment]
Quick fix: in `config.py` in the fastIgnore function put

    def fastIgnore(path):
        if path == "/dev/sdb2":
            return True
        return False

Stick around and I'll troubleshoot.

**Comment by kb100** [comment]
Could you post the output of

    lsblk -no TYPE /dev/sdb2

**Comment by Mahadras** [comment]
output is part

**Comment by kb100** [comment]
See if 55b1a43c0a59d413e173c7bd72f96b64fa2cfdf0 fixes your issue. I have configured it to ignore the swap partition if it exists.

**Comment by Mahadras** [comment]
Yeah this worked! Thank you for your fast help!

**Comment by kb100** [comment]
You are welcome.

Fixed in 55b1a43c0a59d413e173c7bd72f96b64fa2cfdf0
